name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate Github
      uses: joza-solutions/ci-cd/auth-gh-ci-cd@main
      id: auth
      with:
        ci-cd-app-id: ${{ vars.CI_CD_APP_ID }}
        ci-cd-app-private-key: ${{ secrets.CI_CD_APP_PRIVATE_KEY }}
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        token: ${{ steps.auth.outputs.token }}
    - name: Setup Pages
      uses: actions/configure-pages@v6
      with:
        token: ${{ steps.auth.outputs.token }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: "./out"
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{ steps.auth.outputs.token }}
      
